export enum ErrorCode {
  // Wallet-related errors
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS = 'WALLET_ALREADY_EXISTS',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  INVALID_WALLET_STATE = 'INVALID_WALLET_STATE',
  // Transaction-related errors
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  INVALID_TRANSACTION_AMOUNT = 'INVALID_TRANSACTION_AMOUNT',
  SAME_WALLET_TRANSFER = 'SAME_WALLET_TRANSFER',
  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  NEGATIVE_AMOUNT = 'NEGATIVE_AMOUNT',
  AMOUNT_TOO_LARGE = 'AMOUNT_TOO_LARGE',
  MISSING_IDEMPOTENCY_KEY = 'MISSING_IDEMPOTENCY_KEY',
  // System errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  CONCURRENT_MODIFICATION = 'CONCURRENT_MODIFICATION',
  REPOSITORY_ERROR = 'REPOSITORY_ERROR',
}

export const ErrorCodeToHttpStatus: Record<ErrorCode, number> = {
  [ErrorCode.WALLET_NOT_FOUND]: 404,
  [ErrorCode.TRANSACTION_NOT_FOUND]: 404,
  [ErrorCode.WALLET_ALREADY_EXISTS]: 409,
  [ErrorCode.DUPLICATE_TRANSACTION]: 409,
  [ErrorCode.CONCURRENT_MODIFICATION]: 409,
  [ErrorCode.INSUFFICIENT_BALANCE]: 422,
  [ErrorCode.INVALID_WALLET_STATE]: 422,
  [ErrorCode.INVALID_TRANSACTION_AMOUNT]: 422,
  [ErrorCode.SAME_WALLET_TRANSFER]: 422,
  [ErrorCode.VALIDATION_ERROR]: 422,
  [ErrorCode.INVALID_CURRENCY]: 422,
  [ErrorCode.NEGATIVE_AMOUNT]: 422,
  [ErrorCode.AMOUNT_TOO_LARGE]: 422,
  [ErrorCode.MISSING_IDEMPOTENCY_KEY]: 422,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.REPOSITORY_ERROR]: 500,
};
